import React,{useEffect,useMemo,useState} from 'react'
import {supabase} from './supabase'
import './EvaluationMatrix.css'

const LEVELS=[['N','Novice'],['D','Débrouillé'],['A','Averti'],['E','Expert'],['NE','Non évaluable']]
const codes=value=>(Array.isArray(value)?value:[]).map(x=>typeof x==='string'?x:(x.code||x.parent_code||x.comp_code)).filter(Boolean)
export default function EvaluationMatrix({klass,readOnly=false,onClassic}){
 const [students,setStudents]=useState([]),[items,setItems]=useState([]),[competencies,setCompetencies]=useState([]),[context,setContext]=useState(''),[group,setGroup]=useState(''),[search,setSearch]=useState(''),[latest,setLatest]=useState({}),[notes,setNotes]=useState({}),[editing,setEditing]=useState({}),[saving,setSaving]=useState({}),[message,setMessage]=useState('')
 useEffect(()=>{let active=true;Promise.all([
 supabase.from('pp_students').select('id,last_name,first_name,group_name').eq('class_id',klass.id).order('last_name'),
 supabase.from('pp_progression_items').select('id,context_name,period_id,competencies').eq('class_id',klass.id).order('sort_order').order('created_at'),
 supabase.from('pp_competencies').select('code,label,group_code,parent_code').eq('diploma_code',klass.diploma_code).order('sort_order')
 ]).then(([s,i,c])=>{if(!active)return;setStudents(s.data||[]);setItems((i.data||[]).filter(x=>x.context_name));setCompetencies(c.data||[]);setContext(prev=>prev||(localStorage.getItem('pp_last_context_'+klass.id)||i.data?.find(x=>codes(x.competencies).length)?.id||''))}).catch(e=>setMessage(e.message));return()=>{active=false}},[klass.id,klass.diploma_code])
 const detailed=['2MRC','ACCUEIL'].includes(klass.diploma_code)
 const selected=items.find(i=>i.id===context)
 const target=useMemo(()=>{const choices=competencies.filter(c=>detailed?!!c.parent_code:!c.parent_code);if(!selected)return context?[]:choices;const assigned=new Set(codes(selected.competencies));return choices.filter(c=>assigned.has(c.code)||assigned.has(c.parent_code)||( !detailed && competencies.some(child=>child.parent_code===c.code&&assigned.has(child.code)) ))},[selected,context,competencies,detailed])
 const visible=students.filter(s=>(!group||s.group_name===group)&&(!search||((s.last_name||'')+' '+(s.first_name||'')).toLowerCase().includes(search.toLowerCase())))
 const groups=[...new Set(students.map(s=>s.group_name).filter(Boolean))].sort()
 useEffect(()=>{if(!students.length){setLatest({});return}let active=true;supabase.from('pp_teacher_evaluations').select('id,student_id,progression_item_id,competency_code,level,observation,assessed_at,assessed_by').in('student_id',students.map(s=>s.id)).order('assessed_at',{ascending:false}).then(({data,error})=>{if(!active)return;if(error){setMessage(error.message);return}const map={};for(const e of (data||[]).filter(e=>context?e.progression_item_id===context:e.progression_item_id==null)){const key=e.student_id+'|'+e.competency_code;if(!map[key])map[key]=e}setLatest(map);setNotes(Object.fromEntries(Object.entries(map).map(([k,e])=>[k,e.observation||'']))) });return()=>{active=false}},[context,students.map(s=>s.id).join('|')])
 async function save(student,comp,level,observationOnly=false){
  if(readOnly)return;const key=student.id+'|'+comp.code;setSaving(v=>({...v,[key]:true}));setMessage('')
  const {data:{user},error:authError}=await supabase.auth.getUser()
  if(authError||!user){setMessage('Connexion requise.');setSaving(v=>({...v,[key]:false}));return}
  const previous=latest[key],payload={student_id:student.id,progression_item_id:context||null,competency_code:comp.code,competency_label:comp.label,competency_group:comp.group_code,level:observationOnly?(previous?.level||'NE'):level,source_type:context?'context':'other',source_label:selected?.context_name||'Référentiel complet '+klass.diploma_code,observation:notes[key]||null,assessed_by:user.id}
  let result
  if(previous&&previous.assessed_by===user.id)result=await supabase.from('pp_teacher_evaluations').update({level:payload.level,observation:payload.observation,assessed_at:new Date().toISOString()}).eq('id',previous.id).select('id,student_id,competency_code,level,observation,assessed_at,assessed_by').single()
  else result=await supabase.from('pp_teacher_evaluations').insert(payload).select('id,student_id,competency_code,level,observation,assessed_at,assessed_by').single()
  if(result.error)setMessage('Enregistrement refusé : '+result.error.message);else{setLatest(v=>({...v,[key]:result.data}));setEditing(v=>({...v,[key]:false}))}
  setSaving(v=>({...v,[key]:false}))
 }
 return <div className="mcv-evaluation">
 <div className="mcv-eval-controls"><label>Contexte / activité<select value={context} onChange={e=>{setContext(e.target.value);localStorage.setItem('pp_last_context_'+klass.id,e.target.value)}}><option value="">Référentiel complet (toutes les compétences)</option>{items.map(i=><option key={i.id} value={i.id}>{i.period_id} · {i.context_name}</option>)}</select></label><label>Groupe<select value={group} onChange={e=>setGroup(e.target.value)}><option value="">Toute la classe</option>{groups.map(g=><option key={g}>{g}</option>)}</select></label><label>Rechercher<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nom d'élève"/></label></div>
 {(!context||selected)?<><div className="mcv-eval-context-head"><div><small>{selected?'CONTEXTE SÉLECTIONNÉ':'RÉFÉRENTIEL COMPLET'}</small><h2>{selected?.context_name||'Référentiel de compétences — évaluation'}</h2><span>{selected?.period_id||klass.diploma_code} · {target.length} compétence(s) visée(s) · {visible.length} élève(s)</span></div><div className="mcv-eval-legend">{LEVELS.map(([l,n])=><span key={l} className={'mcv-eval-chip pos-'+l}>{l} · {n}</span>)}</div></div>
 <div className="mcv-eval-students-grid">{visible.map(st=><section key={st.id} className="mcv-student-eval-card"><header><strong>{st.last_name} {st.first_name}</strong>{st.group_name&&<small>{st.group_name}</small>}</header><div className="mcv-table-wrap"><table className="mcv-position-table"><thead><tr><th>Compétence</th>{LEVELS.map(([l,n])=><th key={l} className={'pos-'+l}>{l}<small>{n}</small></th>)}<th>Obs.</th></tr></thead><tbody>{target.map(c=>{const key=st.id+'|'+c.code,old=latest[key];return <React.Fragment key={key}><tr><td className="mcv-comp"><b>{c.code}</b><strong>{c.label}</strong>{old&&<small>Dernier : {old.level} · {new Date(old.assessed_at).toLocaleDateString('fr-FR')}</small>}</td>{LEVELS.map(([l,n])=><td key={l} className={'mcv-level-cell pos-'+l}><button disabled={readOnly||saving[key]} type="button" className={old?.level===l?'selected':''} onClick={()=>save(st,c,l)} title={n}>{old?.level===l?'✓':l}</button></td>)}<td><button className="mcv-obs-button" onClick={()=>setEditing(v=>({...v,[key]:!v[key]}))} title="Observation">+</button></td></tr>{editing[key]&&<tr className="mcv-obs-row"><td colSpan={7}><div><input disabled={readOnly} value={notes[key]||''} onChange={e=>setNotes(v=>({...v,[key]:e.target.value}))} placeholder="Observation professeur (facultative)"/>{!readOnly&&<button type="button" disabled={saving[key]} onClick={()=>save(st,c,old?.level||'NE',true)}>Enregistrer la note</button>}</div></td></tr>}</React.Fragment>})}</tbody></table></div></section>)}</div>{!visible.length&&<p>Aucun élève correspondant.</p>}{!target.length&&<p>Ce contexte ne comporte aucune compétence associée. Ajoutez les compétences dans la progression pour pouvoir les évaluer.</p>}</>:<p>Choisissez un contexte pour positionner les élèves sur ses compétences.</p>}
 {message&&<p role="alert" className="mcv-eval-error">{message}</p>}
 </div>
}
