import React,{useEffect,useMemo,useState} from 'react'
import {supabase} from './supabase'
import './PfmpInline.css'
const LEVELS=['N','D','A','E','NE']
export default function PfmpInline({klass,students,periods,readOnly=false,onSaved}){
 const [studentId,setStudentId]=useState(''),[periodId,setPeriodId]=useState(''),[competencies,setCompetencies]=useState([]),[position,setPosition]=useState({}),[company,setCompany]=useState(''),[tutor,setTutor]=useState(''),[strengths,setStrengths]=useState(''),[difficulties,setDifficulties]=useState(''),[objectives,setObjectives]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[savedId,setSavedId]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 useEffect(()=>{setStudentId(students[0]?.id||'')},[klass.id,students.map(s=>s.id).join('|')])
 useEffect(()=>{setPeriodId(periods[0]?.id||'')},[klass.id,periods.map(p=>p.id).join('|')])
 useEffect(()=>{let alive=true;supabase.from('pp_competencies').select('code,label,parent_code,sort_order').eq('diploma_code',klass.diploma_code).order('sort_order').then(({data,error})=>{if(alive){if(error)setMessage(error.message);else setCompetencies(data||[])}});return()=>{alive=false}},[klass.diploma_code])
 useEffect(()=>{let alive=true;setMessage('');setLoading(true);setPosition({});setSavedId('');setCompany('');setTutor('');setStrengths('');setDifficulties('');setObjectives('');setDate(new Date().toISOString().slice(0,10));if(!studentId||!periodId){setLoading(false);return}supabase.from('pp_pfmp_debriefs').select('*').eq('student_id',studentId).eq('pfmp_period_id',periodId).order('created_at',{ascending:false}).limit(1).then(({data,error})=>{if(!alive)return;setLoading(false);if(error){setMessage(error.message);return}const row=data?.[0];if(row){setSavedId(row.id);setPosition(row.gc_positions||{});setCompany(row.company||'');setTutor(row.tutor_name||'');setStrengths(row.strengths||'');setDifficulties(row.difficulties||'');setObjectives(row.next_objectives||'');setDate(row.debrief_date||new Date().toISOString().slice(0,10))}});return()=>{alive=false}},[studentId,periodId])
 const sections=useMemo(()=>competencies.filter(c=>!c.parent_code).map(c=>({...c,children:competencies.filter(x=>x.parent_code===c.code)})),[competencies])
 function setLevel(code,level){if(readOnly)return;setPosition(p=>({...p,[code]:p[code]===level?undefined:level}))}
 async function save(e){e.preventDefault();if(readOnly||busy||!studentId||!periodId)return;setBusy(true);setMessage('');const {data:{user},error:authError}=await supabase.auth.getUser();if(authError||!user){setBusy(false);setMessage('Connexion requise');return}
 const normalized=Object.fromEntries(Object.entries(position).filter(([,v])=>LEVELS.includes(v)))
 const payload={student_id:studentId,pfmp_period_id:periodId,company,tutor_name:tutor,debrief_date:date,strengths,difficulties,next_objectives:objectives,gc_positions:normalized}
 const result=savedId?await supabase.from('pp_pfmp_debriefs').update(payload).eq('id',savedId).select('id').single():await supabase.from('pp_pfmp_debriefs').insert({...payload,teacher_id:user.id}).select('id').single()
 setBusy(false);if(result.error){setMessage('Enregistrement refusé : '+result.error.message);return}setSavedId(result.data.id);setMessage('Débrief PFMP enregistré.');onSaved?.()
 }
 return <section className="pfmp-inline-shell"><header><h2>Débrief PFMP</h2><p>Synthèse inspirée de la grille V14.1 : toutes les compétences ne sont pas nécessairement évaluées à chaque PFMP.</p></header>
 <form onSubmit={save}><div className="pfmp-inline-fields"><label>Classe<input value={klass.name+' · '+klass.school_year} disabled/></label><label>Élève<select value={studentId} onChange={e=>setStudentId(e.target.value)}>{students.map(s=><option value={s.id} key={s.id}>{s.last_name} {s.first_name}</option>)}</select></label><label>PFMP<select value={periodId} onChange={e=>setPeriodId(e.target.value)}>{periods.map(p=><option value={p.id} key={p.id}>{p.label}</option>)}</select></label><label>Entreprise<input disabled={readOnly} value={company} onChange={e=>setCompany(e.target.value)}/></label><label>Tuteur<input disabled={readOnly} value={tutor} onChange={e=>setTutor(e.target.value)}/></label><label>Date du débrief<input type="date" disabled={readOnly} value={date} onChange={e=>setDate(e.target.value)}/></label></div>
 {loading?<p>Chargement du débrief…</p>:<div className="pfmp-inline-competencies">{sections.map(group=><section className="pfmp-inline-group" key={group.code}><h3>{group.code} {group.label}</h3><p>Évaluez uniquement ce qui a réellement été observé pendant la PFMP.</p>{(group.children.length?group.children:[group]).map(c=><div className="pfmp-inline-row" key={c.code}><span>{c.label}</span><div className="pfmp-inline-levels">{LEVELS.map(l=><button type="button" key={l} disabled={readOnly} className={'pfmp-inline-level pfmp-inline-'+l} aria-pressed={position[c.code]===l} onClick={()=>setLevel(c.code,l)}>{l}</button>)}</div></div>)}</section>)}</div>}
 <div className="pfmp-inline-notes"><label>Points forts<textarea disabled={readOnly} rows={3} value={strengths} onChange={e=>setStrengths(e.target.value)}/></label><label>Difficultés / points à consolider<textarea disabled={readOnly} rows={3} value={difficulties} onChange={e=>setDifficulties(e.target.value)}/></label><label className="pfmp-inline-wide">Conseils / objectifs pour la prochaine PFMP<textarea disabled={readOnly} rows={3} value={objectives} onChange={e=>setObjectives(e.target.value)}/></label></div>
 {message&&<p role="status" className="pfmp-inline-message">{message}</p>}{!readOnly&&<button className="btn primary" disabled={busy||loading||!studentId||!periodId} type="submit">{busy?'Enregistrement…':'Enregistrer le débrief PFMP'}</button>}</form>
 </section>
}
