import React,{useEffect,useMemo,useState} from 'react'
import {supabase} from './supabase'
import './SynthesisV14.css'
const LV={N:'Novice',D:'Débrouillé',A:'Averti',E:'Expert',NE:'Non évaluable'}
const levels=['N','D','A','E','NE']
function proposed(rows){const valid=rows.filter(r=>['N','D','A','E'].includes(r.level)).sort((a,b)=>new Date(b.assessed_at)-new Date(a.assessed_at)).slice(0,3);if(!valid.length)return 'NE';for(const r of valid){if(valid.filter(x=>x.level===r.level).length>=2)return r.level}return valid[0].level}
export default function SynthesisV14({klass,readOnly=false}){
 const [mode,setMode]=useState('class'),[students,setStudents]=useState([]),[competencies,setCompetencies]=useState([]),[evaluations,setEvaluations]=useState([]),[self,setSelf]=useState([]),[positions,setPositions]=useState([]),[studentId,setStudentId]=useState(''),[draft,setDraft]=useState({}),[saving,setSaving]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false)
 async function load(){setLoading(true);setError('');const [s,c]=await Promise.all([supabase.from('pp_students').select('id,last_name,first_name').eq('class_id',klass.id).order('last_name'),supabase.from('pp_competencies').select('code,label,group_code,parent_code').eq('diploma_code',klass.diploma_code).order('sort_order')]);if(s.error||c.error){setError((s.error||c.error).message);setLoading(false);return}const people=s.data||[];setStudents(people);setCompetencies((c.data||[]).filter(x=>['2MRC','ACCUEIL','EPC'].includes(klass.diploma_code)?!!x.parent_code:!x.parent_code));setStudentId(prev=>people.some(x=>x.id===prev)?prev:(people[0]?.id||''));const ids=people.map(x=>x.id);if(ids.length){const [ev,se,po]=await Promise.all([supabase.from('pp_teacher_evaluations').select('*').in('student_id',ids).order('assessed_at',{ascending:false}),supabase.from('pp_self_evaluations').select('*').in('student_id',ids).order('assessed_at',{ascending:false}),supabase.from('pp_final_positions').select('*').in('student_id',ids)]);if(ev.error||se.error||po.error)setError((ev.error||se.error||po.error).message);setEvaluations(ev.data||[]);setSelf(se.data||[]);setPositions(po.data||[])}else{setEvaluations([]);setSelf([]);setPositions([])}setLoading(false)}
 useEffect(()=>{load()},[klass.id,klass.diploma_code])
 const evFor=(sid,code)=>evaluations.filter(e=>e.student_id===sid&&(['2MRC','ACCUEIL','EPC'].includes(klass.diploma_code)?e.competency_code===code:(e.parent_competency_code||e.competency_code)===code)).sort((a,b)=>new Date(b.assessed_at)-new Date(a.assessed_at))
 const matrix=useMemo(()=>Object.fromEntries(students.map(st=>[st.id,Object.fromEntries(competencies.map(c=>[c.code,proposed(evFor(st.id,c.code))]))])),[students,competencies,evaluations])
 const counts=useMemo(()=>{const out={N:0,D:0,A:0,E:0,NE:0};for(const st of (mode==='class'?students:students.filter(s=>s.id===studentId))){for(const c of competencies){out[matrix[st.id]?.[c.code]||'NE']++}}return out},[matrix,students,studentId,mode,competencies])
 const total=Object.values(counts).reduce((a,b)=>a+b,0)||1
 const selected=students.find(s=>s.id===studentId)
 const groupNames={...(klass.diploma_code==='AGORA'?{B1:'Relations clients, usagers et adhérents',B2:'Organisation et suivi de la production',B3:'Administration du personnel'}:klass.diploma_code==='EPC'?{B1:'Réception et suivi des commandes',B2:'Mise en valeur et approvisionnement',B3:'Conseil et accompagnement du client'}:{B1:'Gérer l’accueil multicanal',B2:'Gérer l’information et les prestations',B3:'Gérer la relation commerciale'}),A1:'Attitudes professionnelles',A2:'Respect des codes entreprise',A3:'Investissement',C1:'Intégrer la relation client dans un cadre omnicanal',C2:'Assurer le suivi de la relation client',C3:'Collecter et exploiter l’information',AP:'Attitudes professionnelles et savoir-être',G1:'Conseiller et vendre',G2:'Suivre les ventes',G3:'Fidéliser et développer la relation client',G4A:"Animer et gérer l’espace commercial",G4B:"Prospecter et valoriser l’offre commerciale"}
 async function save(c){if(readOnly||!studentId||saving)return;setSaving(c.code);setError('');const {data:{user},error:e}=await supabase.auth.getUser();if(e||!user){setError('Connexion requise');setSaving('');return}const existing=positions.find(p=>p.student_id===studentId&&p.competency_code===c.code);const validated=draft[c.code]||existing?.validated_level||matrix[studentId]?.[c.code]||'NE';const payload={student_id:studentId,competency_code:c.code,competency_label:c.label,competency_group:c.group_code,proposed_level:matrix[studentId]?.[c.code]||'NE',validated_level:validated,updated_by:user.id,updated_at:new Date().toISOString()};const r=await supabase.from('pp_final_positions').upsert(payload,{onConflict:'student_id,competency_code'});setSaving('');if(r.error)setError(r.error.message);else{setPositions(prev=>[...prev.filter(x=>!(x.student_id===studentId&&x.competency_code===c.code)),payload])}}
 return <section className="sv14-shell"><h2>Synthèse des compétences</h2><p>Vue classe ou vue élève. Positionnement : N · Novice, D · Débrouillé, A · Averti, E · Expert, NE · Non évaluable.</p>
 <div className="sv14-tabs"><button className={mode==='class'?'active':''} onClick={()=>setMode('class')}>Vue classe</button><button className={mode==='student'?'active':''} onClick={()=>setMode('student')}>Vue élève</button></div>
 <div className="sv14-controls"><strong>{klass.name} · {klass.school_year}</strong>{mode==='student'&&<select aria-label="Choisir un élève" value={studentId} onChange={e=>{setStudentId(e.target.value);setDraft({})}}>{students.map(s=><option key={s.id} value={s.id}>{s.last_name} {s.first_name}</option>)}</select>}<button type="button" onClick={load}>↻ Recalculer</button></div>
 {error&&<p role="alert" className="sv14-error">{error}</p>}{loading?<p>Calcul en cours…</p>:<>
 {mode==='student'&&<h3>{selected?.last_name} {selected?.first_name}</h3>}
 <div className="sv14-kpis">{levels.map(l=><div key={l} className={'sv14-heat heat-'+l}><b>{counts[l]}</b><span>{l} · {LV[l]}{mode==='class'?' · '+Math.round(100*counts[l]/total)+' %':''}</span></div>)}</div>
 {mode==='class'?<><div className="sv14-info"><b>Vue classe :</b> la matrice synthétise, pour chaque compétence, les observations les plus récentes et la répétition du niveau.</div><div className="sv14-scroll"><table><thead><tr><th>Élève</th>{competencies.map(c=><th key={c.code} title={c.label}>{'GC'+c.code}</th>)}</tr></thead><tbody>{students.map(st=><tr key={st.id}><th>{st.last_name} {st.first_name}</th>{competencies.map(c=><td key={c.code} className={'sv14-heat heat-'+(matrix[st.id]?.[c.code]||'NE')} title={c.label}>{matrix[st.id]?.[c.code]||'NE'}</td>)}</tr>)}</tbody></table></div></>:<>
 <p className="sv14-explain">Proposition = niveau répété au moins 2 fois parmi les 3 observations les plus récentes ; sinon dernière observation. NE est exclu du calcul.</p>
 {Object.entries(groupNames).filter(([g])=>competencies.some(c=>c.group_code===g)).map(([g,name])=><div className="sv14-group" key={g}><h3>{g.replace('G','GC')} · {name}</h3><div className="sv14-scroll"><table><thead><tr><th>Compétence</th><th>Historique récent</th><th>Auto-éval.</th><th>Proposition</th><th>Validation professeur</th></tr></thead><tbody>{competencies.filter(c=>c.group_code===g).map(c=>{const ev=evFor(studentId,c.code),p=matrix[studentId]?.[c.code]||'NE',aut=self.find(x=>x.student_id===studentId&&(x.parent_competency_code||x.competency_code)===c.code),final=positions.find(x=>x.student_id===studentId&&x.competency_code===c.code);return <tr key={c.code}><td><b>{'GC'+c.code}</b><div>{c.label}</div></td><td>{ev.slice(0,5).map(x=><span key={x.id} className={'sv14-chip heat-'+x.level}>{x.level}</span>)}<small>{ev.slice(0,3).map(x=>(x.source_label||x.source_type||'Évaluation')+' · '+new Date(x.assessed_at).toLocaleDateString('fr-FR')).join(' ; ')}</small></td><td>{aut?<span className={'sv14-chip heat-'+aut.level}>{aut.level} · {LV[aut.level]}</span>:'—'}</td><td><span className={'sv14-chip heat-'+p}>{p} · {LV[p]}</span></td><td><select disabled={readOnly} value={draft[c.code]??final?.validated_level??p} onChange={e=>setDraft(v=>({...v,[c.code]:e.target.value}))}>{levels.map(l=><option key={l} value={l}>{l} · {LV[l]}</option>)}</select>{!readOnly&&<button disabled={!!saving} onClick={()=>save(c)}>{saving===c.code?'…':'Valider'}</button>}</td></tr>})}</tbody></table></div></div>)}
 </>}
 </>}</section>
}
